#!/usr/bin/env python3
"""Bake Memory pair faces to RGB565 C arrays (no runtime JPEG/PNG decode)."""

from __future__ import annotations

import struct
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]  # firmware/
SRC = ROOT / "assets" / "memory"
OUT = ROOT / "device" / "src" / "memory_assets_gen.cpp"
SIZE = 96  # matches tools/memory-crop export; cards scale down from this


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def to_rgb565(im: Image.Image, size: int) -> bytes:
    """Opaque RGB565 — photos don't need an alpha plane."""
    im = im.convert("RGBA").resize((size, size), Image.Resampling.LANCZOS)
    n = size * size
    out = bytearray(n * 2)
    for y in range(size):
        for x in range(size):
            r, g, b, a = im.getpixel((x, y))
            if a < 16:
                r = g = b = 0
            struct.pack_into("<H", out, (y * size + x) * 2, rgb565(r, g, b))
    return bytes(out)


def main() -> None:
    pngs = sorted(SRC.glob("*.png"), key=lambda p: p.stem.lower())
    # Skip underscored / hidden authoring scraps.
    pngs = [p for p in pngs if p.stem and p.stem[0] not in "._"]
    if not pngs:
        raise SystemExit(f"No PNGs in {SRC}")

    entries: list[tuple[str, bytes]] = []
    for p in pngs:
        blob = to_rgb565(Image.open(p), SIZE)
        entries.append((p.stem, blob))

    nbytes = SIZE * SIZE * 2
    lines: list[str] = [
        "/* AUTO-GENERATED by scripts/bake_memory_assets.py — do not edit. */",
        "",
        '#include "memory_pack.h"',
        "",
        "#include <cstring>",
        "",
        "namespace wp {",
        "namespace memory_pack {",
        "namespace {",
        "",
        f"constexpr int kCount = {len(entries)};",
        f"constexpr int kSizePx = {SIZE};",
        f"constexpr int kBytes = {nbytes};",
        "",
    ]

    for i, (stem, blob) in enumerate(entries):
        sym = "".join(c if c.isalnum() else "_" for c in stem)
        lines.append(f"static const uint8_t kPix_{sym}[kBytes] = {{")
        for off in range(0, len(blob), 16):
            chunk = blob[off : off + 16]
            hexes = ", ".join(f"0x{b:02x}" for b in chunk)
            lines.append(f"  {hexes},")
        lines.append("};")
        lines.append("")

    lines.append("static const char * const kStems[kCount] = {")
    for stem, _ in entries:
        lines.append(f'  "{stem}",')
    lines.append("};")
    lines.append("")

    lines.append("static const uint8_t * const kPix[kCount] = {")
    for stem, _ in entries:
        sym = "".join(c if c.isalnum() else "_" for c in stem)
        lines.append(f"  kPix_{sym},")
    lines.append("};")
    lines.append("")

    lines.append("static lv_image_dsc_t kDscs[kCount];")
    lines.append("static bool g_ready = false;")
    lines.append("")
    lines.append("void ensure_ready() {")
    lines.append("  if (g_ready) return;")
    lines.append("  for (int i = 0; i < kCount; ++i) {")
    lines.append("    lv_image_dsc_t * d = &kDscs[i];")
    lines.append("    d->header.magic = LV_IMAGE_HEADER_MAGIC;")
    lines.append("    d->header.cf = LV_COLOR_FORMAT_RGB565;")
    lines.append("    d->header.flags = 0;")
    lines.append("    d->header.w = kSizePx;")
    lines.append("    d->header.h = kSizePx;")
    lines.append("    d->header.stride = kSizePx * 2;")
    lines.append("    d->data_size = kBytes;")
    lines.append("    d->data = kPix[i];")
    lines.append("  }")
    lines.append("  g_ready = true;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace")
    lines.append("")
    lines.append("int count() {")
    lines.append("  ensure_ready();")
    lines.append("  return kCount;")
    lines.append("}")
    lines.append("")
    lines.append("const char * stem_at(int i) {")
    lines.append("  ensure_ready();")
    lines.append("  if (i < 0 || i >= kCount) return \"\";")
    lines.append("  return kStems[i];")
    lines.append("}")
    lines.append("")
    lines.append("const lv_image_dsc_t * dsc_at(int i) {")
    lines.append("  ensure_ready();")
    lines.append("  if (i < 0 || i >= kCount) return nullptr;")
    lines.append("  return &kDscs[i];")
    lines.append("}")
    lines.append("")
    lines.append("const lv_image_dsc_t * find_dsc(const char * stem) {")
    lines.append("  ensure_ready();")
    lines.append("  if (!stem || !stem[0]) return nullptr;")
    lines.append("  for (int i = 0; i < kCount; ++i) {")
    lines.append("    if (std::strcmp(kStems[i], stem) == 0) return &kDscs[i];")
    lines.append("  }")
    lines.append("  return nullptr;")
    lines.append("}")
    lines.append("")
    lines.append("}  // namespace memory_pack")
    lines.append("}  // namespace wp")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    kb = len(entries) * nbytes / 1024.0
    print(f"Wrote {OUT} ({len(entries)} faces @ {SIZE}px, {kb:.1f} KB RGB565 in flash)")


if __name__ == "__main__":
    main()
